name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
