name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Problem / motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
